name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: prerequisites
      run: sudo apt-get install libhtmlcxx-dev
    - name: run-cmake
      uses: lukka/run-cmake@v10.7
