name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Create build directory"
      run: mkdir cmake-build-debug
    - name: "Change to build directory"
      run: cd cmake-build-debug
    - name: cmake
      run: cmake ..
